version: '3.8'
services:
  internal:
    image: alpine:latest
    init: true
    networks:
      routed:
    depends_on:
    - router
    volumes:
    - ./data/resolv.conf:/etc/resolv.conf

  router:
    build: ./router
    init: true
    networks:
      routed:
        priority: 1000
      default:
        priority: 1
    volumes:
    - ./data/resolv.conf:/data/resolv.conf
    # environment:
    # - ROUTE_NET=${ROUTE_NET}
    # - ROUTE_GATEWAY=${ROUTE_GATEWAY}
    cap_add:
    - NET_ADMIN

  external:
    init: true
    image: alpine:latest

networks:
  routed:
    driver: macvlan
    # ipam:
    #   config:
    #   - subnet: ${ROUTE_NET}
    #     gateway: ${ROUTE_GATEWAY}
